config/routes.rb
Rails.application.routes.draw do
  get 'pages/about'
  resources :movies
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  root to: redirect("/movies")
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/movie.rb
class Movie < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :set_movie, only: %i[ show edit update destroy ]

  # GET /movies or /movies.json
  def index
    @movies = Movie.all
  end

  # GET /movies/1 or /movies/1.json
  def show
  end

  # GET /movies/new
  def new
    @movie = Movie.new
  end

  # GET /movies/1/edit
  def edit
  end

  # POST /movies or /movies.json
  def create
    @movie = Movie.new(movie_params)

    respond_to do |format|
      if @movie.save
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully created." }
        format.json { render :show, status: :created, location: @movie }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /movies/1 or /movies/1.json
  def update
    respond_to do |format|
      if @movie.update(movie_params)
        format.html { redirect_to movie_url(@movie), notice: "Movie was successfully updated." }
        format.json { render :show, status: :ok, location: @movie }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @movie.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /movies/1 or /movies/1.json
  def destroy
    @movie.destroy

    respond_to do |format|
      format.html { redirect_to movies_url, notice: "Movie was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_movie
      @movie = Movie.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def movie_params
      params.require(:movie).permit(:name, :description, :picture, :rate)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Movies</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body class="container">
  <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">The Movie app</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'movies') %>" href="/movies">Movies</a>
        </li>
        <li class="nav-item">
          <a class="nav-link <%= 'active' if current_page?(controller: 'pages', action: 'about') %>" href="/pages/about">About</a>
        </li>
      </ul>
    </div>
  </div>
</nav>
  <div>
  <%= yield %>
</div>

<footer class="mt-5 text-center">
  <div class="container">
    Movie´s test <%= Time.now.year %>
  </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4" crossorigin="anonymous"></script>
  </body>
</html>

app/views/movies/_form.html.erb
<%= form_with(model: movie) do |form| %>
  <% if movie.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(movie.errors.count, "error") %> prohibited this movie from being saved:</h2>

      <ul>
        <% movie.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div align="center">
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div align="center">
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description %>
  </div>

  <div align="center">
    <%= form.label :picture, style: "display: block" %>
    <%= form.text_field :picture %>
  </div>

  <div align="center">
    <%= form.label :rate, style: "display: block" %>
    <%= form.number_field :rate %>
  </div>

  <div align="center">
    <%= form.submit %>
  </div>
<% end %>

app/views/movies/_movie.html.erb
<div id="<%= dom_id movie %>">
<ul>
<li>
  <p>
    <strong>Name:</strong>
    <%= movie.name %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= movie.description %>
  </p>

  <!--<p>
    <strong>Picture:</strong>
    <%= movie.picture %>
  </p>-->

  <%= image_tag(movie.picture, :alt => "rss feed", :style=>"width:100px;height:60px;") %>

  <p>
    <strong>Rate:</strong>
    <%= movie.rate %>
  </p>
  </li>
  </ul>
</div>

app/views/movies/edit.html.erb
<h1>Editing movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Show this movie", @movie %> |
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Movies</h1>

<div id="movies">
  <% @movies.each do |movie| %>
    <%= render movie %>
    <p>
      <%= link_to "Show this movie", movie %>
    </p>
  <% end %>
</div>

<%= link_to "New movie", new_movie_path %>

app/views/movies/new.html.erb
<h1>New movie</h1>

<%= render "form", movie: @movie %>

<br>

<div>
  <%= link_to "Back to movies", movies_path %>
</div>

app/views/movies/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @movie %>

<div>
  <%= link_to "Edit this movie", edit_movie_path(@movie) %> |
  <%= link_to "Back to movies", movies_path %>
<br/>
<br/>
  <%= button_to "Destroy this movie", @movie, method: :delete %>
</div>

app/views/pages/about.html.erb
<h1>About me</h1>
<p>Hello there! This is my amazing app!</p>